### ISSUE TITLE
New default settings

### ISSUE THREAD

**Issue by tuur29** [mischiminator/RumbleEnhancer#1]
I know this mod is geared more toward players that want the old rumble settings as I noticed the default value of 1 is probably the old intensity.
But I was wondering if you could tell me / guess what the current default settings are? I would like to increase the strength a little (of the now weaker default settings) but it's hard to guess the relative intensities between game reboots.

**Comment by mischiminator** [comment]
Default strength is 1, duration is 25 and pulse is 5
