### ISSUE TITLE
Old version on modsaber site

### ISSUE THREAD

**Issue by tuur29** [mischiminator/RumbleEnhancer#2]
modsaber.com still lists 1.1.0, so when I update my mods, the newer version 1.2.0 gets overwritten. 
No clue if you have to update the mod or if I should contact modsaber.com for this.

**Comment by mischiminator** [comment]
I uploaded v1.2.0 several days ago to modsaber it is still in the approval queue. I have no influence when it will be approved

EDIT: Here is the link to the current version on modsaber.com: https://www.modsaber.org/mod/rumbleenhancerv110/1.2.0
