### ISSUE TITLE
Rumble Won't work

### ISSUE THREAD

**Issue by Truegoldenlegend** [mischiminator/RumbleEnhancer#6]
When this mod is enabled it causes rumble to stop and the setting is messed up it says !NONE for both values in game and after changing them the setting is gone.

**Comment by mischiminator** [comment]
Please send Logs/Rumble Enhancer/latest and Userdata/Rumble Enhancer.json
also so on what plattform do you play

**Comment by Truegoldenlegend** [comment]
Oculus rift using Steam vr and I have tried using -vrmode oculus.
Log:
[INFO @ 22:05:31 | Rumble Enhancer] Object reference not set to an instance of an object
[INFO @ 22:05:32 | Rumble Enhancer] Plugin Version 1.4.3 loaded!
[INFO @ 22:05:38 | Rumble Enhancer] Settings attached!
[INFO @ 22:05:44 | Rumble Enhancer] GameObject attached!
[INFO @ 22:05:44 | Rumble Enhancer] GameObject attached!
[INFO @ 22:05:59 | Rumble Enhancer] Plugin unloaded!
.json:
{
  "RegenerateConfig": false,
  "plugin_name": "RumbleEnhancer"
}

**Comment by mischiminator** [comment]
delete thd json file and try again. the file is from an older version
